// Logic Lab / Patches: source-backed rectangle partition validator with one clue per patch and declared aspect constraints.
import type { Cell } from "@/game/logicPuzzles/core";
import { keyOf } from "@/game/logicPuzzles/core";

export type PatchShape = "square" | "wide" | "tall" | "free";
export type PatchClue = { id: string; cell: Cell; area: number; shape: PatchShape };
export type Patch = { top: number; left: number; height: number; width: number; clueId: string };
export const patchesBoard = { rows: 4, cols: 4 };
export const patchesClues: PatchClue[] = [{ id: "A", cell: { row: 0, col: 0 }, area: 4, shape: "square" }, { id: "B", cell: { row: 0, col: 2 }, area: 2, shape: "wide" }, { id: "C", cell: { row: 1, col: 2 }, area: 2, shape: "wide" }, { id: "D", cell: { row: 2, col: 0 }, area: 2, shape: "tall" }, { id: "E", cell: { row: 2, col: 1 }, area: 4, shape: "square" }, { id: "F", cell: { row: 2, col: 3 }, area: 2, shape: "tall" }];
export const patchesSolution: Patch[] = [{ top: 0, left: 0, height: 2, width: 2, clueId: "A" }, { top: 0, left: 2, height: 1, width: 2, clueId: "B" }, { top: 1, left: 2, height: 1, width: 2, clueId: "C" }, { top: 2, left: 0, height: 2, width: 1, clueId: "D" }, { top: 2, left: 1, height: 2, width: 2, clueId: "E" }, { top: 2, left: 3, height: 2, width: 1, clueId: "F" }];
export const patchCells = (patch: Patch) => Array.from({ length: patch.height * patch.width }, (_, index) => ({ row: patch.top + Math.floor(index / patch.width), col: patch.left + index % patch.width }));
const contains = (patch: Patch, cell: Cell) => cell.row >= patch.top && cell.row < patch.top + patch.height && cell.col >= patch.left && cell.col < patch.left + patch.width;
export function patchMatchesClue(patch: Patch, clue: PatchClue) { const area = patch.height * patch.width; const oneClue = patchesClues.filter((other) => contains(patch, other.cell)).length === 1; const shapeOk = clue.shape === "free" || clue.shape === "square" && patch.height === patch.width || clue.shape === "wide" && patch.width > patch.height || clue.shape === "tall" && patch.height > patch.width; return area === clue.area && contains(patch, clue.cell) && oneClue && shapeOk; }
export function validPatch(patch: Patch, placed: Patch[]) { const clue = patchesClues.find((item) => item.id === patch.clueId); if (!clue || patch.top < 0 || patch.left < 0 || patch.top + patch.height > patchesBoard.rows || patch.left + patch.width > patchesBoard.cols || !patchMatchesClue(patch, clue)) return false; const occupied = new Set(placed.flatMap(patchCells).map(keyOf)); return patchCells(patch).every((cell) => !occupied.has(keyOf(cell))); }
export function solvedPatches(placed: Patch[]) { if (placed.length !== patchesClues.length || new Set(placed.map((patch) => patch.clueId)).size !== patchesClues.length) return false; const used = new Set<string>(); for (const patch of placed) { if (!validPatch(patch, placed.filter((other) => other !== patch))) return false; for (const cell of patchCells(patch)) used.add(keyOf(cell)); } return used.size === patchesBoard.rows * patchesBoard.cols; }
export function patchCandidates(clue: PatchClue) { const choices: Patch[] = []; for (let height = 1; height <= patchesBoard.rows; height += 1) for (let width = 1; width <= patchesBoard.cols; width += 1) for (let top = 0; top <= patchesBoard.rows - height; top += 1) for (let left = 0; left <= patchesBoard.cols - width; left += 1) { const patch = { top, left, height, width, clueId: clue.id }; if (patchMatchesClue(patch, clue)) choices.push(patch); } return choices; }
export function countPatchSolutions(limit = 2) { const candidates = new Map(patchesClues.map((clue) => [clue.id, patchCandidates(clue)])); let count = 0; const search = (placed: Patch[]): void => { if (count >= limit) return; if (placed.length === patchesClues.length) { if (solvedPatches(placed)) count += 1; return; } const openClues = patchesClues.filter((clue) => !placed.some((patch) => patch.clueId === clue.id)).sort((a, b) => (candidates.get(a.id) || []).length - (candidates.get(b.id) || []).length); const clue = openClues[0]; for (const patch of candidates.get(clue.id) || []) if (validPatch(patch, placed)) search([...placed, patch]); }; search([]); return count; }
