// Logic Lab / Tango: binary-grid validation for balance, no triples, and same/different adjacency relations.
import type { Cell } from "@/game/logicPuzzles/core";

export type TangoValue = 0 | 1 | null;
export type TangoGrid = TangoValue[][];
export type TangoRelation = { a: Cell; b: Cell; relation: "same" | "different" };
export const tangoSolution: TangoGrid = [[0, 0, 1, 1, 0, 1], [1, 1, 0, 0, 1, 0], [0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0], [0, 1, 1, 0, 1, 0], [1, 0, 0, 1, 0, 1]];
export const tangoGivens: TangoGrid = [[0, null, 1, null, null, 1], [null, 1, null, 0, 1, null], [0, null, null, 1, null, 1], [1, null, 1, null, 1, null], [null, 1, 1, null, null, 0], [1, null, 0, 1, null, null]];
export const tangoRelations: TangoRelation[] = [{ a: { row: 0, col: 0 }, b: { row: 0, col: 1 }, relation: "same" }, { a: { row: 0, col: 2 }, b: { row: 0, col: 3 }, relation: "same" }, { a: { row: 0, col: 1 }, b: { row: 0, col: 2 }, relation: "different" }, { a: { row: 1, col: 0 }, b: { row: 1, col: 1 }, relation: "same" }, { a: { row: 1, col: 3 }, b: { row: 1, col: 4 }, relation: "different" }, { a: { row: 2, col: 0 }, b: { row: 2, col: 1 }, relation: "different" }, { a: { row: 2, col: 2 }, b: { row: 2, col: 3 }, relation: "different" }, { a: { row: 3, col: 0 }, b: { row: 3, col: 1 }, relation: "different" }, { a: { row: 4, col: 1 }, b: { row: 4, col: 2 }, relation: "same" }, { a: { row: 5, col: 2 }, b: { row: 5, col: 3 }, relation: "different" }, { a: { row: 0, col: 0 }, b: { row: 1, col: 0 }, relation: "different" }, { a: { row: 0, col: 5 }, b: { row: 1, col: 5 }, relation: "different" }, { a: { row: 2, col: 3 }, b: { row: 3, col: 3 }, relation: "different" }, { a: { row: 3, col: 4 }, b: { row: 4, col: 4 }, relation: "same" }];

const lineInvalid = (line: TangoValue[]) => { const known = line.filter((value): value is 0 | 1 => value !== null); if (known.filter((value) => value === 0).length > 3 || known.filter((value) => value === 1).length > 3) return true; for (let index = 0; index < 4; index += 1) if (line[index] !== null && line[index] === line[index + 1] && line[index] === line[index + 2]) return true; return false; };
export function tangoViolations(grid: TangoGrid) { const invalid = new Set<string>(); for (let row = 0; row < 6; row += 1) if (lineInvalid(grid[row])) for (let col = 0; col < 6; col += 1) invalid.add(`${row}:${col}`); for (let col = 0; col < 6; col += 1) { const line = grid.map((row) => row[col]); if (lineInvalid(line)) for (let row = 0; row < 6; row += 1) invalid.add(`${row}:${col}`); } tangoRelations.forEach(({ a, b, relation }) => { const av = grid[a.row][a.col]; const bv = grid[b.row][b.col]; if (av !== null && bv !== null && ((relation === "same" && av !== bv) || (relation === "different" && av === bv))) { invalid.add(`${a.row}:${a.col}`); invalid.add(`${b.row}:${b.col}`); } }); return invalid; }
export function solvedTango(grid: TangoGrid) { return grid.every((row) => row.every((value) => value !== null)) && tangoViolations(grid).size === 0; }
export function countTangoSolutions(seed: TangoGrid, limit = 2) { const grid = seed.map((row) => [...row]); let count = 0; const search = (): void => { if (count >= limit) return; let target: [number, number] | null = null; for (let row = 0; row < 6 && !target; row += 1) for (let col = 0; col < 6; col += 1) if (grid[row][col] === null) { target = [row, col]; break; } if (!target) { if (solvedTango(grid)) count += 1; return; } const [row, col] = target; for (const value of [0, 1] as const) { grid[row][col] = value; if (tangoViolations(grid).size === 0) search(); grid[row][col] = null; } }; search(); return count; }
