// Circuit Shift: DOM HUD with explicit sound consent and browser-local difficulty presets around the Babylon puzzle.
import CircuitShiftCanvas from "@/components/CircuitShiftCanvas";
import { OrbitAudio, type SoundEvent } from "@/game/audio";
import type { CircuitDifficulty, CircuitStatus } from "@/game/circuitShift/CircuitShiftWorld";
import { ArrowLeft, CircuitBoard, RotateCcw, Trophy, Volume2, VolumeX } from "lucide-react";
import { Link } from "wouter";
import { useEffect, useRef, useState } from "react";

const orbitMark = "/manus-storage/toolbox-galaxy-orbit-mark_c8160386.png";
const difficultyOptions: { id: CircuitDifficulty; label: string; detail: string }[] = [{ id: "calm", label: "Calm", detail: "Light scramble · 1× score" }, { id: "standard", label: "Standard", detail: "Full board · 1.35× score" }, { id: "dense", label: "Dense", detail: "Heavy scramble · 1.75× score" }];

export default function CircuitShift() {
  const [score, setScore] = useState(0); const [best, setBest] = useState(0); const [moves, setMoves] = useState(0); const [status, setStatus] = useState<CircuitStatus>("ready"); const [soundOn, setSoundOn] = useState(false); const [difficulty, setDifficulty] = useState<CircuitDifficulty>("standard"); const audio = useRef(new OrbitAudio());
  useEffect(() => () => audio.current.dispose(), []);
  const toggleSound = async () => setSoundOn(await audio.current.setEnabled(!soundOn));
  const start = async () => { if (!soundOn) setSoundOn(await audio.current.setEnabled(true)); window.dispatchEvent(new KeyboardEvent("keydown", { key: " " })); };
  const selectDifficulty = (next: CircuitDifficulty) => { setDifficulty(next); setScore(0); setMoves(0); setStatus("ready"); };
  const activeDifficulty = difficultyOptions.find((option) => option.id === difficulty)!;
  const instruction = status === "ready" ? `${activeDifficulty.label} preset · arrows select · Space rotates` : status === "solved" ? "Signal complete · choose a new preset or press R" : "Rotate tiles until the lime route reaches the output";
  return <section className="orbit-dash-page circuit-shift-page"><CircuitShiftCanvas difficulty={difficulty} callbacks={{ onScore: (next, high) => { setScore(next); setBest(high); }, onStatus: setStatus, onMoves: setMoves, onSound: (event: SoundEvent) => audio.current.play(event) }} /><div className="game-hud"><div className="game-hud__top"><Link href="/games" className="game-back"><ArrowLeft size={16} /> Games bay</Link><div className="game-brand game-brand--circuit"><img src={orbitMark} alt="" /><span><b>Toolbox Galaxy</b><small>Games Bay / Module 03</small></span><i><CircuitBoard size={13} /> Circuit Shift</i></div><div className="game-hud__actions"><button onClick={toggleSound} className={`sound-toggle ${soundOn ? "sound-toggle--on" : ""}`} aria-pressed={soundOn} aria-label={soundOn ? "Turn sound off" : "Turn sound on"}>{soundOn ? <Volume2 size={15} /> : <VolumeX size={15} />} SOUND {soundOn ? "ON" : "OFF"}</button><div className="game-score"><span>MOVES</span><strong>{moves.toString().padStart(2, "0")}</strong></div><div className="game-score game-score--ember"><span>SCORE</span><strong>{score.toString().padStart(3, "0")}</strong></div></div></div><div className="game-hud__bottom"><div className="game-instruction"><RotateCcw size={15} /><span>{instruction}</span></div><div className="best-score"><Trophy size={15} /><span>BEST {best.toString().padStart(3, "0")}</span></div></div>{status !== "playing" && <div className="game-overlay"><p className="mono-label text-[#c7f36b]">{status === "solved" ? "OUTPUT CONNECTED" : "ARCADE MODULE 03"}</p><h1 className="font-display">{status === "solved" ? "Signal received." : "Close the circuit."}</h1><p>{status === "solved" ? `Solved in ${moves} moves on ${activeDifficulty.label}. Change the field profile to run a different puzzle.` : "Select a field profile, then rotate relay tiles to power a continuous lime path from input to output."}</p><div className="circuit-difficulty" role="group" aria-label="Circuit Shift difficulty">{difficultyOptions.map((option) => <button key={option.id} type="button" onClick={() => selectDifficulty(option.id)} className={difficulty === option.id ? "circuit-difficulty__option circuit-difficulty__option--active" : "circuit-difficulty__option"}><b>{option.label}</b><span>{option.detail}</span></button>)}</div><button onClick={start} className="signal-button">{status === "solved" ? `Run ${activeDifficulty.label} with sound` : `Start ${activeDifficulty.label} with sound`}</button></div>}</div></section>;
}
