// Orbital Workbench: an honest contact route that becomes active only when the same-origin PHP endpoint is configured.
import AppShell from "@/components/AppShell";
import { contactApiConfigured, submitContact } from "@/lib/contactApi";
import { useState } from "react";

export default function Contact() {
  const [form, setForm] = useState({ name: "", email: "", subject: "Tool feedback", message: "" }); const [status, setStatus] = useState(""); const [sending, setSending] = useState(false);
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!contactApiConfigured) return; setSending(true); setStatus(""); try { const response = await submitContact(form); setStatus(`Feedback received${response.requestId ? ` · ref ${response.requestId}` : ""}.`); setForm({ name: "", email: "", subject: "Tool feedback", message: "" }); } catch (error) { setStatus(error instanceof Error ? error.message : "The feedback request could not be sent."); } finally { setSending(false); } };
  return <AppShell><section className="page-section contact-page"><p className="mono-label text-[#c7f36b]">CONTACT / FEEDBACK LOOP</p><h1 className="font-display mt-4 text-5xl font-semibold tracking-[-0.065em]">Help shape the next module.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/62">The legacy contact route is retired. This form is deliberately enabled only after the secure same-origin PHP endpoint is configured on Hostinger.</p><div className="contact-panel"><div className="console-divider"><span>01 · MESSAGE</span><span>{contactApiConfigured ? "API LINK READY" : "HOSTINGER API PENDING"}</span><span>02 · DELIVERY</span></div><form onSubmit={send} className="contact-form"><label>Name<input required maxLength={80} value={form.name} onChange={(event) => update("name", event.target.value)} /></label><label>Email<input required type="email" maxLength={254} value={form.email} onChange={(event) => update("email", event.target.value)} /></label><label className="wide-field">Subject<input required maxLength={140} value={form.subject} onChange={(event) => update("subject", event.target.value)} /></label><label className="wide-field">Message<textarea required minLength={10} maxLength={3000} rows={7} value={form.message} onChange={(event) => update("message", event.target.value)} /></label><div className="contact-actions">{contactApiConfigured ? <button disabled={sending} className="signal-button">{sending ? "Sending…" : "Send feedback"}</button> : <a className="signal-button" href="mailto:support@toolboxgalaxy.com?subject=Toolbox%20Galaxy%20feedback">Email support instead</a>}<span aria-live="polite" className="contact-status">{status || (contactApiConfigured ? "Messages are sent through the configured Hostinger endpoint." : "The secure form endpoint has not been configured yet.")}</span></div></form></div></section></AppShell>;
}
