// Orbital Workbench: direct full-screen Games Bay puzzle modules with source-verified rules, date-local challenge profiles, and explicit assist controls.
import GameAudioControls from "@/components/GameAudioControls";
import { OrbitAudio } from "@/game/audio";
import { isPuzzleFieldComplete, markPuzzleFieldComplete } from "@/lib/puzzleCompletion";
import { baseToDisplay, displayToBase, getLogicDaily, type LogicDaily } from "@/game/logicPuzzles/daily";
import { miniSudokuProfiles } from "@/game/logicPuzzles/dailyProfiles";
import { cloneGrid, sameCell } from "@/game/logicPuzzles/core";
import type { Cell } from "@/game/logicPuzzles/core";
import { miniSudokuSolution, solvedSudoku, sudokuConflicts, type SudokuGrid } from "@/game/logicPuzzles/miniSudoku";
import { queensRegions, queensSolution, solvedQueens, queensViolations, type QueenState } from "@/game/logicPuzzles/queens";
import { solvedTango, tangoGivens, tangoRelations, tangoSolution, tangoViolations, type TangoGrid, type TangoValue } from "@/game/logicPuzzles/tango";
import { patchCells, patchesBoard, patchesClues, patchesSolution, solvedPatches, validPatch, type Patch } from "@/game/logicPuzzles/patches";
import { solvedZip, validZipPath, zipEditionBank, zipEditionForDate } from "@/game/logicPuzzles/zip";
import { matchesWendWord, solvedWend, validWendPath, wendGrid, wendWords, wordFromPath } from "@/game/logicPuzzles/wend";
import { ArrowLeft, CalendarDays, Check, Crown, Lightbulb, Moon, RotateCcw, Sparkles, Sun, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { MutableRefObject, ReactNode } from "react";
import { Link, useRoute } from "wouter";

const orbitMark = "/manus-storage/toolbox-galaxy-orbit-mark_c8160386.png";
const demoMode = () => new URLSearchParams(window.location.search).has("demo");
const cellKey = (row: number, col: number) => `${row}:${col}`;
const emptyQueens = () => Array.from({ length: 6 }, () => Array.from({ length: 6 }, () => "empty" as QueenState));
const difficultyDetail: Record<LogicDaily["difficulty"], string> = { calm: "GUIDED START · 3 ASSISTS", standard: "STANDARD FIELD · 2 ASSISTS", dense: "DENSE FIELD · 1 ASSIST" };
const initialTango = (daily: LogicDaily): TangoGrid => { const next = cloneGrid(tangoGivens) as TangoGrid; if (daily.difficulty === "calm") [[0, 1], [2, 2]].forEach(([row, col]) => { next[row][col] = tangoSolution[row][col]; }); return next; };
const initialQueens = (daily: LogicDaily) => { const next = emptyQueens(); if (daily.difficulty === "calm") next[0][queensSolution[0]] = "queen"; return next; };
const firstEmpty = (grid: SudokuGrid) => grid.flatMap((line, row) => line.map((value, col) => ({ row, col, value }))).find(({ value }) => value === 0);

function usePuzzleCompletion(slug: string, daily: LogicDaily, solved: boolean, demo: boolean) {
  const [completed, setCompleted] = useState(() => isPuzzleFieldComplete(slug, daily.id));
  useEffect(() => { if (solved && !demo) { markPuzzleFieldComplete(slug, daily.id); setCompleted(true); } }, [daily.id, demo, slug, solved]);
  return completed;
}

function PuzzleFrame({ eyebrow, title, rules, children, solved, onReset, onHint, audio, daily, feedback, progress, completedOnDevice }: { eyebrow: string; title: string; rules: string; children: ReactNode; solved: boolean; onReset: () => void; onHint: () => void; audio: MutableRefObject<OrbitAudio>; daily: LogicDaily; feedback: string; progress: { label: string; value: number; total: number }; completedOnDevice: boolean }) {
  const progressComplete = progress.value === progress.total;
  return <section className={`logic-game-page logic-game-page--${daily.difficulty}`}><header className="logic-game-hud"><Link href="/games" className="game-back"><ArrowLeft size={16} /> Games bay</Link><div className="logic-game-brand"><img src={orbitMark} alt="" /><span><b>TOOLBOX / GALAXY</b><small>{eyebrow}</small></span></div><div className="logic-game-actions"><GameAudioControls audio={audio} music /><button type="button" className="logic-action" onClick={onHint}><Lightbulb size={15} /> Hint</button><button type="button" className="logic-action" onClick={onReset}><RotateCcw size={15} /> Reset</button></div></header><main className="logic-game-stage"><div className="logic-game-intro"><div><p className="mono-label text-[#c7f36b]">DAILY FIELD / {daily.id}</p><h1 className="font-display">{title}</h1><p>{rules}</p></div><div className="logic-daily-card"><CalendarDays size={17} /><span><b>{daily.label}</b><small>{difficultyDetail[daily.difficulty]}</small></span><i>{daily.difficulty.toUpperCase()}</i></div></div><div className="logic-game-console"><div className="logic-console-head"><span>CONSTRAINT FIELD / LIVE</span><i /><span>LOCAL ONLY / NO NETWORK</span></div><div className={`logic-progress ${progressComplete ? "logic-progress--complete" : ""}`} aria-live="polite"><span>{progress.label}</span><strong>{progress.value} / {progress.total}</strong><i>{solved ? "SOLVED NOW" : completedOnDevice ? "COMPLETED ON THIS DEVICE" : "IN PROGRESS"}</i></div>{solved && <aside className="logic-game-solved" role="status"><Check size={19} /><span><b>Constraint system complete.</b> Every local rule passes. {completedOnDevice ? "This daily field is saved as completed on this device." : "Demo verification is visible only and does not save progress."}</span><button type="button" onClick={onReset}>Play again</button></aside>}{children}<div className="logic-console-foot"><span>HINT / REVEALS ONE VERIFIED NEXT MOVE</span><span>{feedback}</span></div></div></main><footer className="logic-game-footer"><span>POINTER + KEYBOARD / READY</span><span>DATE-LOCAL EDITION / {daily.id}</span></footer></section>;
}

function MiniSudokuPuzzle() {
  const audio = useRef(new OrbitAudio()); const demo = demoMode(); const daily = useMemo(() => getLogicDaily(), []); const givens = useMemo(() => cloneGrid(miniSudokuProfiles[daily.difficulty]), [daily.difficulty]); const [grid, setGrid] = useState<SudokuGrid>(() => cloneGrid(givens)); const [feedback, setFeedback] = useState("Choose a cell, then enter 1–6. Every 2×3 region has its own heavy border."); const solved = solvedSudoku(grid); const conflicts = sudokuConflicts(grid); const solvedRef = useRef(false);
  useEffect(() => () => audio.current.dispose(), []);
  useEffect(() => { if (!demo) return; const cells = Array.from({ length: 36 }, (_, index) => ({ row: Math.floor(index / 6), col: index % 6 })).filter(({ row, col }) => givens[row][col] === 0); let step = 0; const timer = window.setInterval(() => { if (step >= cells.length) return window.clearInterval(timer); const { row, col } = cells[step++]; setGrid((current) => { const next = cloneGrid(current); next[row][col] = miniSudokuSolution[row][col]; return next; }); }, 110); return () => window.clearInterval(timer); }, [demo, givens]);
  useEffect(() => { if (solved && !solvedRef.current && !demo) audio.current.play("puzzleSolve"); solvedRef.current = solved; }, [solved, demo]);
  const setValue = (row: number, col: number, value: number) => { if (givens[row][col]) return; setGrid((current) => { const next = cloneGrid(current); next[row][col] = value; return next; }); audio.current.play("rotate"); };
  const hint = () => { const target = firstEmpty(grid); if (!target) return setFeedback("No blank cells remain; the validator is checking the final constraint set."); setValue(target.row, target.col, miniSudokuSolution[target.row][target.col]); setFeedback(`Hint: row ${target.row + 1}, column ${target.col + 1} is ${miniSudokuSolution[target.row][target.col]}. Its row, column, and 2×3 region are now the next focus.`); };
  const completedOnDevice = usePuzzleCompletion("mini-sudoku", daily, solved, demo); const filled = grid.flat().filter(Boolean).length;
  return <PuzzleFrame eyebrow="LOGIC MODULE 01 / 6×6" title="Mini Sudoku" rules="Fill digits 1–6 so every row, column, and all six 2×3 regions contain each digit exactly once." solved={solved} onReset={() => { setGrid(cloneGrid(givens)); setFeedback("Board reset to this date’s verified clue profile."); }} onHint={hint} audio={audio} daily={daily} feedback={feedback} progress={{ label: "DIGITS PLACED", value: filled, total: 36 }} completedOnDevice={completedOnDevice}><div className="logic-board-layout sudoku-layout"><div className="sudoku-grid" role="grid" aria-label="Mini Sudoku grid">{Array.from({ length: 36 }, (_, index) => { const displayRow = Math.floor(index / 6); const displayCol = index % 6; const base = displayToBase(displayRow, displayCol, 6, daily.transform); const value = grid[base.row][base.col]; return <button key={cellKey(displayRow, displayCol)} type="button" role="gridcell" className={`sudoku-cell ${givens[base.row][base.col] ? "sudoku-cell--given" : ""} ${conflicts.has(cellKey(base.row, base.col)) ? "puzzle-cell--invalid" : ""} ${displayCol === 2 ? "sudoku-cell--box-right" : ""} ${displayRow === 1 || displayRow === 3 ? "sudoku-cell--box-bottom" : ""}`} disabled={Boolean(givens[base.row][base.col])} onClick={() => setValue(base.row, base.col, value === 6 ? 1 : value + 1)} onKeyDown={(event) => { const numeric = Number(event.key); if (numeric >= 1 && numeric <= 6) { event.preventDefault(); setValue(base.row, base.col, numeric); } if (event.key === "Backspace" || event.key === "Delete") setValue(base.row, base.col, 0); }} aria-label={`Row ${displayRow + 1}, column ${displayCol + 1}, ${value || "empty"}`}>{value || ""}</button>; })}</div><aside className="logic-game-note"><Lightbulb size={17} /><p><b>INPUT</b> Click to cycle, or use keys 1–6 for direct entry.</p><p><b>HINT</b> Reveals one verified value and tells you its 2×3 region.</p><p><b>LIVE CHECK</b> Duplicate digits are visible immediately.</p></aside></div></PuzzleFrame>;
}

function TangoPuzzle() {
  const audio = useRef(new OrbitAudio()); const demo = demoMode(); const daily = useMemo(() => getLogicDaily(), []); const givens = useMemo(() => initialTango(daily), [daily]); const [grid, setGrid] = useState<TangoGrid>(() => cloneGrid(givens) as TangoGrid); const [feedback, setFeedback] = useState("Use the visible = and × boundary markers to eliminate one symbol at a time."); const solved = solvedTango(grid); const invalid = tangoViolations(grid); const solvedRef = useRef(false);
  useEffect(() => () => audio.current.dispose(), []);
  useEffect(() => { if (!demo) return; const cells = Array.from({ length: 36 }, (_, index) => ({ row: Math.floor(index / 6), col: index % 6 })).filter(({ row, col }) => givens[row][col] === null); let step = 0; const timer = window.setInterval(() => { if (step >= cells.length) return window.clearInterval(timer); const { row, col } = cells[step++]; setGrid((current) => { const next = cloneGrid(current) as TangoGrid; next[row][col] = tangoSolution[row][col]; return next; }); }, 125); return () => window.clearInterval(timer); }, [demo, givens]);
  useEffect(() => { if (solved && !solvedRef.current && !demo) audio.current.play("puzzleSolve"); solvedRef.current = solved; }, [solved, demo]);
  const cycle = (row: number, col: number, exact?: TangoValue) => { if (givens[row][col] !== null) return; setGrid((current) => { const next = cloneGrid(current) as TangoGrid; next[row][col] = exact === undefined ? (next[row][col] === null ? 0 : next[row][col] === 0 ? 1 : null) : exact; return next; }); audio.current.play("rotate"); };
  const hint = () => { const incorrect = Array.from(invalid).map((key) => key.split(":").map(Number) as [number, number]).find(([row, col]) => givens[row][col] === null); const empty = grid.flatMap((line, row) => line.map((value, col) => ({ row, col, value }))).find(({ row, col, value }) => value === null && givens[row][col] === null); const target = incorrect ? { row: incorrect[0], col: incorrect[1] } : empty; if (!target) return setFeedback("All Tango cells are set. Check the line balance and boundary markers."); cycle(target.row, target.col, tangoSolution[target.row][target.col]); setFeedback(`Hint: row ${target.row + 1}, column ${target.col + 1} is ${tangoSolution[target.row][target.col] === 0 ? "moon" : "sun"}.`); };
  const completedOnDevice = usePuzzleCompletion("tango", daily, solved, demo); const filled = grid.flat().filter((value) => value !== null).length;
  return <PuzzleFrame eyebrow="LOGIC MODULE 02 / BINARY" title="Tango" rules="Balance both symbols in every line, avoid triples, and respect linked equal or different pairs." solved={solved} onReset={() => { setGrid(cloneGrid(givens) as TangoGrid); setFeedback("Board reset to this date’s binary field."); }} onHint={hint} audio={audio} daily={daily} feedback={feedback} progress={{ label: "SYMBOLS PLACED", value: filled, total: 36 }} completedOnDevice={completedOnDevice}><div className="logic-board-layout tango-layout"><div className="tango-board" role="grid" aria-label="Tango binary puzzle">{Array.from({ length: 36 }, (_, index) => { const displayRow = Math.floor(index / 6); const displayCol = index % 6; const base = displayToBase(displayRow, displayCol, 6, daily.transform); const value = grid[base.row][base.col]; return <button key={cellKey(displayRow, displayCol)} type="button" role="gridcell" className={`tango-cell ${givens[base.row][base.col] !== null ? "tango-cell--given" : ""} ${invalid.has(cellKey(base.row, base.col)) ? "puzzle-cell--invalid" : ""}`} disabled={givens[base.row][base.col] !== null} onClick={() => cycle(base.row, base.col)} onKeyDown={(event) => { if (event.key === "0") cycle(base.row, base.col, 0); if (event.key === "1") cycle(base.row, base.col, 1); if (event.key === "Backspace" || event.key === "Delete") cycle(base.row, base.col, null); }} aria-label={`Row ${displayRow + 1}, column ${displayCol + 1}, ${value === null ? "empty" : value === 0 ? "moon" : "sun"}`}>{value === 0 ? <Moon size={23} /> : value === 1 ? <Sun size={23} /> : ""}</button>; })}{tangoRelations.map((relation, index) => { const a = baseToDisplay(relation.a.row, relation.a.col, 6, daily.transform); const b = baseToDisplay(relation.b.row, relation.b.col, 6, daily.transform); const horizontal = a.row === b.row; const left = horizontal ? (Math.min(a.col, b.col) + 1) / 6 * 100 : (a.col + .5) / 6 * 100; const top = horizontal ? (a.row + .5) / 6 * 100 : (Math.min(a.row, b.row) + 1) / 6 * 100; return <span key={index} className={`tango-relation tango-relation--${horizontal ? "horizontal" : "vertical"}`} style={{ left: `${left}%`, top: `${top}%` }} aria-hidden="true">{relation.relation === "same" ? "=" : "×"}</span>; })}</div><aside className="logic-game-note"><Lightbulb size={17} /><p><b>INPUT</b> Click cycles moon → sun → blank; keys 0 and 1 enter directly.</p><p><b>HINT</b> Corrects one flagged or open cell.</p><p><b>LIVE CHECK</b> Every 3/3 line, triple, and boundary link is tested.</p></aside></div></PuzzleFrame>;
}

function QueensPuzzle() {
  const audio = useRef(new OrbitAudio()); const demo = demoMode(); const daily = useMemo(() => getLogicDaily(), []); const [grid, setGrid] = useState<QueenState[][]>(() => initialQueens(daily)); const [feedback, setFeedback] = useState("Use marks to test eliminations; only Crowns count toward the six region constraints."); const solved = solvedQueens(grid); const invalid = queensViolations(grid); const solvedRef = useRef(false);
  useEffect(() => () => audio.current.dispose(), []);
  useEffect(() => { if (!demo) return; let row = 0; const timer = window.setInterval(() => { if (row >= 6) return window.clearInterval(timer); const active = row++; setGrid((current) => { const next = current.map((line) => [...line]); next[active][queensSolution[active]] = "queen"; return next; }); }, 175); return () => window.clearInterval(timer); }, [demo]);
  useEffect(() => { if (solved && !solvedRef.current && !demo) audio.current.play("puzzleSolve"); solvedRef.current = solved; }, [solved, demo]);
  const cycle = (row: number, col: number) => { setGrid((current) => { const next = current.map((line) => [...line]); next[row][col] = next[row][col] === "empty" ? "marked" : next[row][col] === "marked" ? "queen" : "empty"; return next; }); audio.current.play("rotate"); };
  const hint = () => { const wrong = grid.flatMap((line, row) => line.map((value, col) => ({ row, col, value }))).find(({ row, col, value }) => value === "queen" && queensSolution[row] !== col); if (wrong) { setGrid((current) => { const next = current.map((line) => [...line]); next[wrong.row][wrong.col] = "empty"; return next; }); return setFeedback(`Hint: cleared the excess Crown at row ${wrong.row + 1}, column ${wrong.col + 1}.`); } const row = queensSolution.findIndex((col, currentRow) => grid[currentRow][col] !== "queen"); if (row < 0) return setFeedback("All six verified Crown locations are already present."); setGrid((current) => { const next = current.map((line) => [...line]); next[row][queensSolution[row]] = "queen"; return next; }); setFeedback(`Hint: a Crown belongs in row ${row + 1}, column ${queensSolution[row] + 1}.`); };
  const completedOnDevice = usePuzzleCompletion("queens", daily, solved, demo); const crownCount = grid.flat().filter((value) => value === "queen").length;
  return <PuzzleFrame eyebrow="LOGIC MODULE 03 / REGIONS" title="Queens" rules="Place one Crown in every row, column, and colored region. Crowns cannot touch, even diagonally." solved={solved} onReset={() => { setGrid(initialQueens(daily)); setFeedback("Board reset to this date’s region assignment."); }} onHint={hint} audio={audio} daily={daily} feedback={feedback} progress={{ label: "CROWNS PLACED", value: crownCount, total: 6 }} completedOnDevice={completedOnDevice}><div className="logic-board-layout queens-layout"><div className="queens-board" role="grid" aria-label="Queens region puzzle">{Array.from({ length: 36 }, (_, index) => { const displayRow = Math.floor(index / 6); const displayCol = index % 6; const base = displayToBase(displayRow, displayCol, 6, daily.transform); const state = grid[base.row][base.col]; return <button key={cellKey(displayRow, displayCol)} type="button" role="gridcell" className={`queen-cell queen-cell--region-${queensRegions[base.row][base.col]} ${invalid.has(cellKey(base.row, base.col)) ? "puzzle-cell--invalid" : ""}`} onClick={() => cycle(base.row, base.col)} onKeyDown={(event) => { if (event.key === " " || event.key === "Enter") { event.preventDefault(); cycle(base.row, base.col); } }} aria-label={`Row ${displayRow + 1}, column ${displayCol + 1}, region ${queensRegions[base.row][base.col] + 1}, ${state}`}>{state === "queen" ? <Crown size={23} /> : state === "marked" ? <X size={16} /> : ""}</button>; })}</div><aside className="logic-game-note"><Lightbulb size={17} /><p><b>INPUT</b> Click cycles blank → mark → Crown.</p><p><b>HINT</b> Removes an excess Crown or confirms the next location.</p><p><b>LIVE CHECK</b> Rows, columns, regions, and all adjacent cells are checked.</p></aside></div></PuzzleFrame>;
}

function PatchesPuzzle() {
  const audio = useRef(new OrbitAudio()); const demo = demoMode(); const daily = useMemo(() => getLogicDaily(), []); const [placed, setPlaced] = useState<Patch[]>(() => daily.difficulty === "calm" ? [patchesSolution[0]] : []); const [anchor, setAnchor] = useState<Cell | null>(null); const [feedback, setFeedback] = useState("Choose a clue cell, then an opposite corner. This is the larger 6×6 partition field."); const solved = solvedPatches(placed);
  useEffect(() => () => audio.current.dispose(), []);
  useEffect(() => { if (!demo) return; let index = 0; const timer = window.setInterval(() => { if (index >= patchesSolution.length) return window.clearInterval(timer); setPlaced((current) => [...current, patchesSolution[index++]]); }, 210); return () => window.clearInterval(timer); }, [demo]);
  const select = (cell: Cell) => { if (!anchor) { setAnchor(cell); return setFeedback("Anchor set. Choose the opposite corner for this clue-owned rectangle."); } const top = Math.min(anchor.row, cell.row); const left = Math.min(anchor.col, cell.col); const patch: Patch = { top, left, height: Math.abs(anchor.row - cell.row) + 1, width: Math.abs(anchor.col - cell.col) + 1, clueId: "" }; const inside = patchesClues.filter((clue) => clue.cell.row >= top && clue.cell.row < top + patch.height && clue.cell.col >= left && clue.cell.col < left + patch.width); setAnchor(null); if (inside.length !== 1) return setFeedback("A patch must contain exactly one clue. Choose a different rectangle."); patch.clueId = inside[0].id; const without = placed.filter((existing) => existing.clueId !== patch.clueId); if (!validPatch(patch, without)) return setFeedback("That rectangle fails its clue area, aspect, overlap, or boundary rule."); setPlaced([...without, patch]); setFeedback(`Patch ${patch.clueId} locked locally.`); audio.current.play("rotate"); };
  const hint = () => { const target = patchesSolution.find((patch) => !placed.some((item) => item.clueId === patch.clueId)); if (!target) return setFeedback("All required rectangles are already placed."); setPlaced((current) => [...current.filter((item) => item.clueId !== target.clueId), target]); setFeedback(`Hint: revealed complete rectangle ${target.clueId}.`); };
  const completedOnDevice = usePuzzleCompletion("patches", daily, solved, demo); const locked = new Set(placed.map((patch) => patch.clueId)).size;
  return <PuzzleFrame eyebrow="LOGIC MODULE 04 / 6×6 RECTANGLES" title="Patches" rules="Partition all 36 cells into clue-owned rectangles. Each rectangle contains exactly one clue and meets its stated area and orientation." solved={solved} onReset={() => { setPlaced(daily.difficulty === "calm" ? [patchesSolution[0]] : []); setAnchor(null); setFeedback("Board reset. Choose one clue cell, then an opposite corner."); }} onHint={hint} audio={audio} daily={daily} feedback={feedback} progress={{ label: "PATCHES LOCKED", value: locked, total: patchesSolution.length }} completedOnDevice={completedOnDevice}><div className="logic-board-layout patches-layout"><div className="patches-grid" role="grid" aria-label="Patches rectangle partition puzzle" style={{ gridTemplateColumns: `repeat(${patchesBoard.cols}, minmax(0, 1fr))` }}>{Array.from({ length: patchesBoard.rows * patchesBoard.cols }, (_, index) => { const display = { row: Math.floor(index / patchesBoard.cols), col: index % patchesBoard.cols }; const cell = displayToBase(display.row, display.col, patchesBoard.rows, daily.transform); const owner = placed.findIndex((patch) => patchCells(patch).some((item) => sameCell(item, cell))); const clue = patchesClues.find((item) => sameCell(item.cell, cell)); const selected = anchor && sameCell(anchor, cell); return <button key={cellKey(display.row, display.col)} type="button" role="gridcell" className={`patch-cell ${owner >= 0 ? `patch-cell--${owner % 6}` : ""} ${selected ? "patch-cell--anchor" : ""}`} onClick={() => select(cell)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); select(cell); } }} aria-label={`Row ${display.row + 1}, column ${display.col + 1}${clue ? `, clue ${clue.area} ${clue.shape}` : ""}`}>{clue && <span><b>{clue.area}</b><small>{clue.shape === "square" ? "□" : clue.shape === "wide" ? "↔" : clue.shape === "tall" ? "↕" : "·"}</small></span>}</button>; })}</div><aside className="logic-game-note"><Lightbulb size={17} /><p><b>INPUT</b> Select two opposite corners around a single clue.</p><p><b>HINT</b> Locks one verified clue-owned rectangle.</p><p><b>LIVE CHECK</b> Area, aspect, overlap, one-clue ownership, and full coverage apply.</p></aside></div></PuzzleFrame>;
}

function ZipPuzzle() {
  const audio = useRef(new OrbitAudio()); const demo = demoMode(); const daily = useMemo(() => getLogicDaily(), []); const editionOverride = new URLSearchParams(window.location.search).get("edition"); const edition = useMemo(() => zipEditionBank.find((item) => item.id === editionOverride) ?? zipEditionForDate(daily.id), [daily.id, editionOverride]); const editionDaily = useMemo(() => ({ ...daily, difficulty: edition.difficulty }), [daily, edition.difficulty]); const startingPath = () => edition.difficulty === "calm" ? edition.solution.slice(0, 3) : [edition.board.numbers[0].cell]; const [path, setPath] = useState<Cell[]>(startingPath); const [feedback, setFeedback] = useState("Plan around forks and walls: each checkpoint must be reached in order while all 36 cells remain coverable."); const solved = solvedZip(path, edition.board);
  useEffect(() => () => audio.current.dispose(), []);
  useEffect(() => { if (!demo) return; let index = 1; const timer = window.setInterval(() => { if (index >= edition.solution.length) return window.clearInterval(timer); setPath(edition.solution.slice(0, ++index)); }, 95); return () => window.clearInterval(timer); }, [demo, edition]);
  const select = (cell: Cell) => { const existing = path.findIndex((item) => sameCell(item, cell)); if (existing >= 0) { setPath(path.slice(0, existing + 1)); return setFeedback("Path rewound to that station."); } const next = [...path, cell]; if (!validZipPath(next, edition.board)) return setFeedback("That move is not an open orthogonal step in the required numbered order."); setPath(next); setFeedback(`${next.length}/${edition.board.rows * edition.board.cols} cells connected.`); audio.current.play("rotate"); };
  const hint = () => { let correct = 0; while (correct < path.length && sameCell(path[correct], edition.solution[correct])) correct += 1; const revealed = Math.min(correct + 1, edition.solution.length); setPath(edition.solution.slice(0, revealed)); setFeedback(correct < path.length ? "Hint: cleared the path after its first mistake and revealed the next correct step." : `Hint: revealed path step ${revealed}.`); };
  const completedOnDevice = usePuzzleCompletion(`zip-${edition.id}`, daily, solved, demo);
  return <PuzzleFrame eyebrow={`LOGIC MODULE 05 / ${edition.id.replace("zip-", "").toUpperCase()} / 6×6`} title="Zip" rules={`Edition ${edition.id.replace("zip-", "").toUpperCase()}: choose carefully at each fork, pass ${edition.board.numbers.length} stations in order, cover all 36 cells, and never cross a wall.`} solved={solved} onReset={() => { setPath(startingPath()); setFeedback("Path reset. Re-plan the forks before committing a corridor."); }} onHint={hint} audio={audio} daily={editionDaily} feedback={feedback} progress={{ label: "PATH CELLS", value: path.length, total: edition.solution.length }} completedOnDevice={completedOnDevice}><div className="logic-board-layout zip-layout"><div className="zip-grid" role="grid" aria-label={`Zip ${edition.id} strategic ordered path puzzle`} style={{ gridTemplateColumns: `repeat(${edition.board.cols}, minmax(0, 1fr))` }}>{Array.from({ length: edition.board.rows * edition.board.cols }, (_, index) => { const display = { row: Math.floor(index / edition.board.cols), col: index % edition.board.cols }; const cell = displayToBase(display.row, display.col, edition.board.rows, daily.transform); const pathIndex = path.findIndex((item) => sameCell(item, cell)); const station = edition.board.numbers.find((item) => sameCell(item.cell, cell)); return <button key={cellKey(display.row, display.col)} type="button" role="gridcell" className={`zip-cell ${pathIndex >= 0 ? "zip-cell--active" : ""}`} onClick={() => select(cell)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); select(cell); } }} aria-label={`Row ${display.row + 1}, column ${display.col + 1}${station ? `, station ${station.value}` : ""}${pathIndex >= 0 ? `, path step ${pathIndex + 1}` : ""}`}>{station && <b>{station.value}</b>}{pathIndex >= 0 && <i>{pathIndex + 1}</i>}</button>; })}{edition.board.blockedEdges.map(([a, b], index) => { const first = baseToDisplay(a.row, a.col, edition.board.rows, daily.transform); const second = baseToDisplay(b.row, b.col, edition.board.rows, daily.transform); const horizontal = first.row !== second.row; const left = horizontal ? first.col / edition.board.cols * 100 : (Math.min(first.col, second.col) + 1) / edition.board.cols * 100; const top = horizontal ? (Math.min(first.row, second.row) + 1) / edition.board.rows * 100 : first.row / edition.board.rows * 100; return <span key={index} className={`zip-wall zip-wall--${horizontal ? "horizontal" : "vertical"}`} style={{ left: `${left}%`, top: `${top}%` }} aria-hidden="true" />; })}</div><aside className="logic-game-note"><Lightbulb size={17} /><p><b>INPUT</b> At a fork, consider which corridor still lets you reach the next station and cover every cell.</p><p><b>HINT</b> Erases after the first wrong step, then reveals the next correct cell.</p><p><b>LIVE CHECK</b> Edition route, walls, repeats, station order, and full 36-cell coverage are tested.</p></aside></div></PuzzleFrame>;
}

function WendPuzzle() {
  const audio = useRef(new OrbitAudio()); const demo = demoMode(); const daily = useMemo(() => getLogicDaily(), []); const initialFound = () => daily.difficulty === "calm" ? [wendWords[0].word] : []; const [found, setFound] = useState<string[]>(initialFound); const [active, setActive] = useState<Cell[]>([]); const [hintCell, setHintCell] = useState<Cell | null>(null); const [feedback, setFeedback] = useState("Trace a listed word one adjacent letter at a time. Every tile belongs to exactly one word."); const foundWords = wendWords.filter((word) => found.includes(word.word)); const solved = solvedWend(foundWords);
  useEffect(() => () => audio.current.dispose(), []);
  useEffect(() => { if (!demo) return; let index = 0; const timer = window.setInterval(() => { if (index >= wendWords.length) return window.clearInterval(timer); setFound((current) => [...current, wendWords[index++].word]); }, 290); return () => window.clearInterval(timer); }, [demo]);
  const select = (cell: Cell) => { if (foundWords.some((word) => word.path.some((item) => sameCell(item, cell)))) return; const existing = active.findIndex((item) => sameCell(item, cell)); if (existing >= 0) { setActive(active.slice(0, existing + 1)); return setFeedback("Word trace rewound."); } const next = [...active, cell]; if (!validWendPath(next)) return setFeedback("Wend words move orthogonally and cannot reuse a tile."); const match = wendWords.find((word) => !found.includes(word.word) && matchesWendWord(next, word)); if (match) { setFound([...found, match.word]); setActive([]); setHintCell(null); setFeedback(`${match.word} verified. Continue until every tile is assigned.`); audio.current.play("rotate"); return; } setActive(next); setFeedback(`${wordFromPath(next)} — keep tracing or click a traced letter to backtrack.`); };
  const hint = () => { if (active.length) { setActive([]); return setFeedback("Hint: cleared the unfinished trace so you can start an available target cleanly."); } const word = wendWords.find((item) => !found.includes(item.word)); if (!word) return setFeedback("All target words are already verified."); setHintCell(word.path[0]); setFeedback(`Hint: ${word.word} begins at row ${word.path[0].row + 1}, column ${word.path[0].col + 1}.`); };
  const completedOnDevice = usePuzzleCompletion("wend", daily, solved, demo);
  return <PuzzleFrame eyebrow="LOGIC MODULE 06 / WORD COVER" title="Wend" rules="Find every listed word by orthogonal tracing. Words cannot overlap and, together, must use every letter tile exactly once." solved={solved} onReset={() => { setFound(initialFound()); setActive([]); setHintCell(null); setFeedback("Board reset. Trace one target word at a time."); }} onHint={hint} audio={audio} daily={daily} feedback={feedback} progress={{ label: "WORDS VERIFIED", value: foundWords.length, total: wendWords.length }} completedOnDevice={completedOnDevice}><div className="logic-board-layout wend-layout"><div><div className="wend-targets" aria-label="Target words">{wendWords.map((word) => { const complete = found.includes(word.word); return <span key={word.word} className={complete ? "wend-target--found" : ""}>{complete && <Check size={12} aria-hidden="true" />} {word.word}{complete && <small>FOUND</small>}</span>; })}</div><div className="wend-grid" role="grid" aria-label="Wend exact-cover word puzzle">{Array.from({ length: 25 }, (_, index) => { const displayRow = Math.floor(index / 5); const displayCol = index % 5; const cell = displayToBase(displayRow, displayCol, 5, daily.transform); const letter = wendGrid[cell.row][cell.col]; const wordIndex = foundWords.findIndex((word) => word.path.some((item) => sameCell(item, cell))); const activeIndex = active.findIndex((item) => sameCell(item, cell)); const hinted = hintCell && sameCell(hintCell, cell); return <button key={cellKey(displayRow, displayCol)} type="button" role="gridcell" className={`wend-cell ${wordIndex >= 0 ? `wend-cell--${wordIndex}` : ""} ${activeIndex >= 0 ? "wend-cell--active" : ""} ${hinted ? "wend-cell--hint" : ""}`} onClick={() => select(cell)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); select(cell); } }} aria-label={`Row ${displayRow + 1}, column ${displayCol + 1}, letter ${letter}${wordIndex >= 0 ? `, assigned to ${foundWords[wordIndex].word}` : ""}`}>{letter}</button>; })}</div></div><aside className="logic-game-note"><Lightbulb size={17} /><p><b>INPUT</b> Click neighboring letters in order; click a trace to backtrack.</p><p><b>HINT</b> Clears an active mistake or highlights the next target’s first tile.</p><p><b>LIVE CHECK</b> Exact target spellings and complete non-overlap stay local.</p></aside></div></PuzzleFrame>;
}

export default function LogicPuzzle() {
  const [, legacy] = useRoute("/games/logic/:slug"); const [, direct] = useRoute("/games/:slug"); const slug = legacy?.slug ?? direct?.slug;
  if (slug === "mini-sudoku") return <MiniSudokuPuzzle />; if (slug === "tango") return <TangoPuzzle />; if (slug === "queens") return <QueensPuzzle />; if (slug === "patches") return <PatchesPuzzle />; if (slug === "zip") return <ZipPuzzle />; if (slug === "wend") return <WendPuzzle />;
  return <section className="logic-game-page"><div className="logic-game-stage"><p className="mono-label">MODULE NOT DEPLOYED</p><h1 className="font-display">This verified puzzle field is unavailable.</h1><Link href="/games" className="signal-button">Return to Games Bay</Link></div></section>;
}
