// Signal Switch: DOM telemetry HUD and explicit browser-sound permission frame around a Babylon relay board.
import SignalSwitchCanvas from "@/components/SignalSwitchCanvas";
import GameAudioControls from "@/components/GameAudioControls";
import { OrbitAudio, type SoundEvent } from "@/game/audio";
import { ArrowLeft, Radio, RotateCcw, Trophy } from "lucide-react";
import { Link } from "wouter";
import { useEffect, useRef, useState } from "react";

export default function SignalSwitch() { const [score, setScore] = useState(0); const [best, setBest] = useState(0); const [timer, setTimer] = useState(2.4); const [status, setStatus] = useState<"ready" | "playing" | "over">("ready"); const audio = useRef(new OrbitAudio()); useEffect(() => () => audio.current.dispose(), []); const start = async () => { if (!audio.current.isEnabled()) await audio.current.setEnabled(true); window.dispatchEvent(new KeyboardEvent("keydown", { key: " " })); }; const instruction = status === "ready" ? "Match the active pad · arrows, WASD, or tap" : status === "over" ? "Signal dropped · press Space or R to restart" : "Route the ember packet before the timer empties"; return <section className="orbit-dash-page signal-switch-page"><SignalSwitchCanvas callbacks={{ onScore: (next, high) => { setScore(next); setBest(high); }, onStatus: setStatus, onTimer: setTimer, onSound: (event: SoundEvent) => audio.current.play(event) }} /><div className="game-hud"><div className="game-hud__top"><Link href="/games" className="game-back"><ArrowLeft size={16} /> Games bay</Link><div className="game-brand"><Radio size={14} /> SIGNAL SWITCH</div><div className="game-hud__actions"><GameAudioControls audio={audio} /><div className="game-score"><span>TIME</span><strong>{timer.toFixed(1)}</strong></div><div className="game-score"><span>SCORE</span><strong>{score.toString().padStart(2, "0")}</strong></div></div></div><div className="game-hud__bottom"><div className="game-instruction"><RotateCcw size={15} /><span>{instruction}</span></div><div className="best-score"><Trophy size={15} /><span>BEST {best.toString().padStart(2, "0")}</span></div></div>{status !== "playing" && <div className="game-overlay"><p className="mono-label text-[#c7f36b]">{status === "over" ? "LINK INTERRUPTED" : "ARCADE MODULE 02"}</p><h1 className="font-display">{status === "over" ? "Rebuild the link." : "Route the signal."}</h1><p>{status === "over" ? `You completed ${score} relay${score === 1 ? "" : "s"}.` : "Match the lime relay pad before the amber packet expires. Use keys or tap the board."}</p><button onClick={start} className="signal-button">{status === "over" ? "Reconnect" : "Start relay"}</button></div>}</div></section>; }
