import { countSudokuSolutions, miniSudokuEditionBank, miniSudokuEditionForDate, solvedSudoku } from "../client/src/game/logicPuzzles/miniSudoku";
import { countTangoSolutions, solvedTango, tangoGivens, tangoSolution, tangoViolations } from "../client/src/game/logicPuzzles/tango";
import { countQueensSolutions, queensSolution, solvedQueens, queensViolations, type QueenState } from "../client/src/game/logicPuzzles/queens";
import { countPatchSolutions, patchesSolution, solvedPatches } from "../client/src/game/logicPuzzles/patches";
import { countZipSolutions, solvedZip, zipEditionBank, zipEditionForDate } from "../client/src/game/logicPuzzles/zip";
import { solvedWend, validWendPath, wendWords } from "../client/src/game/logicPuzzles/wend";
import { baseToDisplay, displayToBase, getLogicDaily } from "../client/src/game/logicPuzzles/daily";

const assert = (condition: unknown, message: string) => { if (!condition) throw new Error(message); };
assert(miniSudokuEditionBank.length === 7, "Mini Sudoku must ship seven independently authored editions"); const sudokuSolutions = new Set<string>(); const sudokuMasks = new Set<string>(); miniSudokuEditionBank.forEach((edition) => { const solutionSignature = edition.solution.flat().join(""); const maskSignature = edition.givens.flat().map((value) => value ? "1" : "0").join(""); assert(!sudokuSolutions.has(solutionSignature), `${edition.id} must not reuse another solution grid`); assert(!sudokuMasks.has(maskSignature), `${edition.id} must not reuse another clue layout`); sudokuSolutions.add(solutionSignature); sudokuMasks.add(maskSignature); assert(solvedSudoku(edition.solution), `${edition.id} solution must validate`); assert(countSudokuSolutions(edition.givens) === 1, `${edition.id} givens must have one solution`); }); const duplicateSudoku = miniSudokuEditionBank[0].solution.map((row) => [...row]); duplicateSudoku[0][1] = duplicateSudoku[0][0]; assert(!solvedSudoku(duplicateSudoku), "Mini Sudoku duplicate must fail"); const sudokuWeek = new Set(Array.from({ length: 7 }, (_, index) => miniSudokuEditionForDate(`2026-08-${String(24 + index).padStart(2, "0")}`).id)); assert(sudokuWeek.size === 7, "Seven consecutive local dates must select all Mini Sudoku editions");
assert(solvedTango(tangoSolution), "Tango solution must validate");
assert(countTangoSolutions(tangoGivens) === 1, "Tango givens must have one solution");
const tripleTango = tangoSolution.map((row) => [...row]); tripleTango[0][2] = 0; assert(tangoViolations(tripleTango).size > 0, "Tango triple must fail");
const queensGrid: QueenState[][] = Array.from({ length: 6 }, () => Array.from({ length: 6 }, () => "empty")); queensSolution.forEach((col, row) => { queensGrid[row][col] = "queen"; }); assert(solvedQueens(queensGrid), "Queens solution must validate"); assert(countQueensSolutions() === 1, "Queens regions must have one solution"); const adjacentQueens = queensGrid.map((row) => [...row]); adjacentQueens[0][2] = "queen"; assert(queensViolations(adjacentQueens).size > 0, "Adjacent/duplicate queens must fail");
assert(solvedPatches(patchesSolution), "Patches authored partition must validate"); assert(countPatchSolutions() === 1, "Patches clues must have one partition"); assert(!solvedPatches(patchesSolution.slice(0, -1)), "Patches incomplete cover must fail");
assert(zipEditionBank.length === 7, "Zip must ship seven independently authored editions"); const zipRoutes = new Set<string>(); zipEditionBank.forEach((edition) => { const route = edition.solution.map((cell) => `${cell.row}:${cell.col}`).join(","); assert(!zipRoutes.has(route), `${edition.id} must not repeat a previous route`); zipRoutes.add(route); assert(solvedZip(edition.solution, edition.board), `${edition.id} route must validate`); assert(countZipSolutions(edition.board) === 1, `${edition.id} must have one valid path`); assert(!solvedZip([...edition.solution.slice(0, 3), edition.solution[4]], edition.board), `${edition.id} skipped cell must fail`); }); const zipWeek = new Set(Array.from({ length: 7 }, (_, index) => zipEditionForDate(`2026-08-${String(24 + index).padStart(2, "0")}`).id)); assert(zipWeek.size === 7, "Seven consecutive local dates must select all Zip editions");
assert(validWendPath(wendWords[0].path), "Wend authored word path must be orthogonal"); assert(solvedWend(wendWords), "Wend authored paths must exactly cover grid"); assert(!solvedWend(wendWords.slice(0, -1)), "Wend incomplete word cover must fail");
const date = new Date(2026, 7, 26); const firstDaily = getLogicDaily(date); const secondDaily = getLogicDaily(date); assert(firstDaily.id === secondDaily.id && firstDaily.difficulty === secondDaily.difficulty && firstDaily.transform === secondDaily.transform, "Daily field must be deterministic for one local date"); ([0, 1, 2, 3] as const).forEach((transform) => { const display = baseToDisplay(1, 2, 6, transform); const base = displayToBase(display.row, display.col, 6, transform); assert(base.row === 1 && base.col === 2, "Daily board transform must round-trip coordinates"); });
console.log("Logic puzzle validators passed: Mini Sudoku, Tango, Queens, Patches, Zip, Wend.");
