// Orbital Workbench: a docked local-only calendar converts verified daily-field completions into an inspectable weekly streak without collecting player data.
import { weeklyLogicSummary } from "@/lib/weeklyLogicStreak";
import { CalendarDays, ChevronLeft, ChevronRight, Flame, ShieldCheck, Trophy } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const dateRange = (start: string, end: string) => { const begin = new Date(`${start}T12:00:00`); const finish = new Date(`${end}T12:00:00`); const sameMonth = begin.getMonth() === finish.getMonth(); const label = new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }); return sameMonth ? `${new Intl.DateTimeFormat("en", { month: "long" }).format(begin)} ${begin.getDate()}–${finish.getDate()}` : `${label.format(begin)} – ${label.format(finish)}`; };

export default function WeeklyLogicCalendar() {
  const [weekOffset, setWeekOffset] = useState(0); const [revision, setRevision] = useState(0);
  useEffect(() => { const sync = () => setRevision((value) => value + 1); window.addEventListener("storage", sync); return () => window.removeEventListener("storage", sync); }, []);
  const summary = useMemo(() => weeklyLogicSummary(new Date(), weekOffset), [revision, weekOffset]);
  return <section className="weekly-logic-calendar" aria-labelledby="weekly-logic-title"><header><div><p className="mono-label text-[#c7f36b]">VERIFIED DAILY EDITIONS / THIS BROWSER</p><h2 id="weekly-logic-title" className="font-display">Local streak calendar.</h2><p>Only finished Mini Sudoku, Tango, Queens, Patches, Zip, and Wend edition fields count here. Game opens, demos, and visual orientation changes never add activity.</p></div><div className="weekly-logic-actions"><button type="button" onClick={() => setWeekOffset((value) => value - 1)} aria-label="Show previous week"><ChevronLeft size={17} /></button><div><CalendarDays size={17} /><b>{dateRange(summary.weekStart, summary.weekEnd)}</b><small>{weekOffset === 0 ? "CURRENT WEEK" : `${weekOffset > 0 ? "+" : ""}${weekOffset} WEEK`}</small></div><button type="button" onClick={() => setWeekOffset((value) => value + 1)} aria-label="Show next week"><ChevronRight size={17} /></button><button type="button" className="weekly-logic-today" onClick={() => setWeekOffset(0)} disabled={weekOffset === 0}>Today</button></div></header><div className="weekly-logic-metrics"><span><Flame size={16} /><b>{summary.currentStreak}</b><small>CURRENT STREAK</small></span><span><Trophy size={16} /><b>{summary.longestStreak}</b><small>LONGEST STREAK</small></span><span><ShieldCheck size={16} /><b>{summary.completedDays}</b><small>VERIFIED DAYS</small></span><span><CalendarDays size={16} /><b>{summary.totalCompletedFields}</b><small>FIELDS COMPLETE</small></span></div><div className="weekly-logic-days" role="list" aria-label={`Weekly local activity for ${dateRange(summary.weekStart, summary.weekEnd)}`}>{summary.days.map((day) => <div key={day.id} role="listitem" className={`weekly-logic-day ${day.isToday ? "weekly-logic-day--today" : ""} ${day.completedFields.length ? "weekly-logic-day--complete" : ""} ${day.isFuture ? "weekly-logic-day--future" : ""}`} aria-label={`${day.id}: ${day.completedFields.length ? `${day.completedFields.length} verified field${day.completedFields.length === 1 ? "" : "s"} complete` : day.isFuture ? "future local date" : "no verified field completed"}`}><small>{day.shortLabel}</small><b>{day.dayNumber}</b><i>{day.completedFields.length ? `${day.completedFields.length}/6` : "—"}</i><span>{day.completedFields.length ? day.completedFields.map((slug) => <em key={slug}>{slug === "mini-sudoku" ? "S" : slug === "tango" ? "T" : slug === "queens" ? "Q" : slug === "patches" ? "P" : slug === "zip" ? "Z" : "W"}</em>) : day.isFuture ? "FUTURE" : "LOCAL"}</span></div>)}</div><footer><span>LOCAL STORAGE / NO ACCOUNT / NO NETWORK</span><span>{summary.completedDays ? "Completed days are counted once, even when several edition fields finish on the same day." : "No verified daily field is complete on this device yet—finish any genuine edition to light a local day."}</span></footer></section>;
}
